### ISSUE TITLE
Create a database schema.

### ISSUE THREAD

**Issue by santosderek** [santosderek/Vitality#12]
Look at databases like MariaDB, mongodb?, And others that is easy to use with flask (I think there's documentation on this), and create a basic schema with a hard coded (for now) admin user.

Put the schema file into the root directory. (Next to the setup.py file.) 

Possible tables. **Add what you think is needed too!**

- User table
    - Username.
    - Passwords, encrypted.
    - User workouts.
    - User location (optional).

- Workout table
    - Name
    - Dificulty
    - Unique ID (Automatically assigned number)
    - About information

- Trainer Table
    - Trainer name
   - Trainer location
    - Trainer times

**Comment by elijahlaruffa** [comment]
https://flask-pymongo.readthedocs.io/en/latest/

https://docs.mongodb.com/manual/core/databases-and-collections/

**Comment by santosderek** [comment]
MongoDB with Flask-pyMongo looks very promising! 

If you can get a working first draft of a database file and are able to show it loaded onto MongoDB locally or through Atlas let me know. Also if you need a domain for Atlas I can point some of my domains to it and have something like atlas.dyrenex.com (my domain) instead of just raw IP addresses.

**Comment by santosderek** [comment]
I just added Configuration.py to get credentials in one localized location (configuration.json). Please use Configuration.py when adding the server URI (or any credentials you need) and edit what you have to, to get it working. 

Reference pull request #16
