### ISSUE TITLE
Look into Google Maps API and what we need to get started.

### ISSUE THREAD

**Issue by santosderek** [santosderek/Vitality#13]
Look into Google Maps API and what we need to get started. Report findings to this issue.

**Comment by santosderek** [comment]
Bryson's Research so far: 

https://developers.google.com/maps/documentation/javascript/places#place_search_requests

https://developers.google.com/places/web-service/search#FindPlaceRequests

https://developers.google.com/maps/billing/gmp-billing#nearby-search

**Comment by BrysonParker1796** [comment]
I think this simple tutorial may be helpful to what we intend to do with the maps API. With a little tweaking, we could probably implement this for listing nearby gyms/trainers: 
https://codelabs.developers.google.com/codelabs/google-maps-simple-store-locator/#0

**Comment by santosderek** [comment]
Going to pivot you for now. Looks like we have a good starting place for this and I need help with user functionality. Look at #28 for your new Issue. 

Closing for now. Will come back to in the near future.
