### ISSUE TITLE
See map of nearby trainers

### ISSUE THREAD

**Issue by santosderek** [santosderek/Vitality#170]
**What would you like to add?**
See a map of nearby trainers and gyms in my area so that I am able to pick the closest gym.

Probably will need to show a user a map and pass that location into mongodb. 
I believe mongodb has a way to filter geolocation. 

- [x] Have a user select a location within the signup page.
- [x] User should be able to update their location on the user settings page. 
- [ ] Generate a map of nearby users from their given location. 
- [x] Update user class to contain `lng` and `lat` variables 
- [ ] Any new functions / functionality within database and flask should have unit tests in respective files.

**Comment by BrysonParker1796** [comment]
https://docs.mongodb.com/manual/tutorial/geospatial-tutorial/
This tutorial is probably what we should base the implementation on.
