### ISSUE TITLE
Select recommended workouts based on user provided data

### ISSUE THREAD

**Issue by santosderek** [santosderek/Vitality#205]
- [x] Show recommended workouts above the search bar when searching for a workout. 
- [x] Use the Youtube API to fetch workout videos from pre-defined workout channels. 
  - [x] On search query, use the user provided text to search these channels as well.

**Comment by elijahlaruffa** [comment]
https://www.youtube.com/watch?v=th5_9woFJmk&t=1055s

**Comment by elijahlaruffa** [comment]
https://github.com/googleapis/google-api-python-client

**Comment by elijahlaruffa** [comment]
https://googleapis.github.io/google-api-python-client/docs/dyn/youtube_v3.html
