### ISSUE TITLE
Create an Events class 

### ISSUE THREAD

**Issue by santosderek** [santosderek/Vitality#88]
**Is your feature request related to a problem? Please describe.**
- [ ] Create a file called `events.py` that holds all the events variables found in the UML

**Comment by jiyoungsin** [comment]
Hey this seems like a great issue for me could you please assign this to me and point me to the UML diagram?

**Comment by santosderek** [comment]
Hello @jiyoungsin ! Sorry, this is actually a repo for a senior project so we're not allowed to take outside help with this. I probably should have said that in the Readme. 

I'll update the Readme to reflect this. Sorry for the confusion!
